[tool.poetry]
name = "meerkat_dl"
version = "0.1.0"
description = "A Deep Learning Framework Just for Fun!"
authors = ["Raghav Saboo"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
